console.log('sayhello');
console.log(123);
console.log(true);
var greeting= 'hello';
console.log(greeting);
console.log([1,2,3,4]);
console.log({a:1,b:2});
console.table({a:1,b:2});
console.error("this is error");
console.clear();
console.warn("this is warning");
console.time('hello');
  console.log("hello Woorld");
  console.timeEnd("hello");
alert('hello');